apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guard
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.hosts.guard }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guard
                port:
                  number: {{ .Values.guard.service.port }}
