apiVersion: v1
kind: Service
metadata:
  name: guard
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: guard
  ports:
    - name: http
      port: {{ .Values.guard.service.port }}
      targetPort: 8787
